### ISSUE TITLE
Doesn't handle scalable icons

### ISSUE THREAD

**Issue by hadess** [flathub/linux-store-backend#10] opened 2018-09-10 11:17 UTC
The Flash player only ships with a scalable icon, and the backend is incapable of converting it to a PNG for the Flathub website to be able to use it.

See https://github.com/flathub/com.adobe.Flash-Player-Projector/issues/2

**Comment by eszlari** [comment] 2018-09-10 12:04
It works in:
https://github.com/flathub/org.openshot.OpenShot
https://flathub.org/apps/details/org.openshot.OpenShot

**Comment by hadess** [comment] 2018-09-10 12:49
> It works in:
> https://github.com/flathub/org.openshot.OpenShot
> https://flathub.org/apps/details/org.openshot.OpenShot

The Openshot SVG file declares a bitmap size of 290x290. The Flash player one is 240x234, so it's likely the code doesn't like upscaling icons (even though those are SVGs, so should scale up just fine).

**Comment by jgarciao** [comment] 2018-09-10 13:00
linux-store-backend is just the website backend and is not responsible of creating the repo's appstream file or of resizing and processing icons or screenshots. 

@ramcq  or @alexlarsson  might know the best place to request this feature

**Comment by hadess** [comment] 2018-09-10 13:46
> linux-store-backend is just the website backend and is not responsible of creating the repo's appstream file or of resizing and processing icons or screenshots.

The fact that it *requires* those but isn't able to use the existing scalable icons strikes me as odd.

**Comment by jgarciao** [comment] 2018-09-10 14:13
The website backend is an independent application not part of the the build process. It's a client, like gnome-software. It sees only what is informed in the repository's appstream file. 

So, is there is not `<icon>` tag for your app there is no way it could in any form find your svg file and transform it

>The fact that it requires those but isn't able to use the existing scalable icons strikes me as odd.

I added minimal checks here because the build process wasn't enforcing the requirements so we had many apps without icons, descriptions or even without name.

**Comment by jgarciao** [comment] 2019-01-22 11:03
Here is more information about the icon requirements:

https://github.com/flathub/org.gnome.Weather/issues/2#issuecomment-456026946

I'm closing this issue, as is not something that I can fix in the backend at this time

**Closed by jgarciao** 2019-01-22 11:03 UTC

**Comment by hadess** [comment] 2019-01-22 12:49
> I'm closing this issue, as is not something that I can fix in the backend at this time

"Fixing it" isn't what I was asking for though. Packagers want clear, upfront, warnings about things that would be unsupported. Simply closing hiding bugs under the rug doesn't help anyone. It won't help the reviewers who have to do support for new packages, trying to figure out why icons don't show up, or you, re-explaining the same thing over and over.

**Comment by ramcq** [comment] 2019-01-22 13:15
The root cause seems to be twofold - firstly appdata doesn't have a place to put scalable icons at all, so the appstream compose command which augments the app developer's appstream with the stuff from the desktop file doesn't seek to add/preserve this, it just looks for a 128 and a 64 icon. Secondly, and this could be a bug somewhere in appstream-glib, Flatpak, the runtimes, or something, it seems like as-compose is supposed to be able to find a scalable icon and then resize it to these two, but this doesn't seem to be happening.
